name: setup-ninja

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: test
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        version: [ '1.11.1-sym1' ]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
      - uses: ./
        with:
          version: '${{ matrix.version }}'
      - shell: bash
        run: '[[ "${{ matrix.version }}" == "$(ninja --version)"* ]]'
